import { RegimeDefinition, RegimeKey } from '../types.ts';

export const REGIMES: Record<Exclude<RegimeKey, 'COMBINED'>, RegimeDefinition> = {
  FLASH_CRASH: {
    key: 'FLASH_CRASH',
    label: 'Flash Crash',
    badge: 'badge-flash',
    cardCls: 'flash',
    drift: -0.0010,
    vol: 0.014,
    meanRev: 0.01,
    candleBody: 0.30,
    atrBase: 0.55,
    tp2: 0.50,
    desc: 'Severe liquidation waterfall (ADX > 35 & 1H Red HTF). Symmetrical sit-out in 100% Cash.',
    entryOffset: 0.15,
    tp1: 0.35,
    slCoeff: 1.5,
    sizePct: 0.00,
  },
  MARKET_CHOP: {
    key: 'MARKET_CHOP',
    label: 'Market Chop',
    badge: 'badge-chop',
    cardCls: 'chop',
    drift: 0.0000,
    vol: 0.004,
    meanRev: 0.18,
    candleBody: 0.45,
    atrBase: 0.22,
    tp2: 0.65,
    desc: 'Tight consolidation around VWMA (<0.3% / ADX < 20). Symmetrical sit-out in 100% Cash.',
    entryOffset: 0.10,
    tp1: 0.35,
    slCoeff: 1.5,
    sizePct: 0.00,
  },
  RANGE_BOUND_SUPPORT: {
    key: 'RANGE_BOUND_SUPPORT',
    label: 'Range Bound / Support',
    badge: 'badge-range',
    cardCls: 'range',
    drift: 0.0001,
    vol: 0.008,
    meanRev: 0.06,
    candleBody: 0.55,
    atrBase: 0.35,
    tp2: 0.55,
    desc: 'Support bounce wicks with Close - 8¢ limit entry (15m TTL), 55¢ TP2 & +15¢ runner floor.',
    entryOffset: 0.08,
    tp1: 0.35,
    slCoeff: 1.5,
    sizePct: 0.4167,
  },
  BULL_TREND_DRIFT: {
    key: 'BULL_TREND_DRIFT',
    label: 'Bull Trend / Drift',
    badge: 'badge-bull',
    cardCls: 'bull',
    drift: 0.0006,
    vol: 0.009,
    meanRev: 0.02,
    candleBody: 0.65,
    atrBase: 0.38,
    tp2: 1.10,
    desc: 'Steady uptrend with pullback wicks. Close - 8¢ limit entry, extended TP2 targets ($1.10 runner).',
    entryOffset: 0.08,
    tp1: 0.35,
    slCoeff: 1.5,
    sizePct: 0.4167,
  },
};

export const ORDERED_REGIMES: Exclude<RegimeKey, 'COMBINED'>[] = [
  'FLASH_CRASH',
  'MARKET_CHOP',
  'RANGE_BOUND_SUPPORT',
  'BULL_TREND_DRIFT',
];
